#!/bin/bash

id="$(xinput list | grep "SYNA.*Touchpad" | sed -n 's/.*id\=\([0-9]\+\).*/\1/p')"
prop_id=$(xinput list-props $id | grep "Tapping Enabled ([0-9]\+)" | sed -n 's/.*(\([0-9]\+\)).*/\1/p')

xinput set-prop $id $prop_id 1

